# Brewfile for Monero
# A homebrew Brewfile installs all required dependencies in one shot
# see https://coderwall.com/p/afmnbq/homebrew-s-new-feature-brewfiles
#     https://github.com/Homebrew/homebrew-bundle
# execute brew bundle in the directory containing the Brewfile

brew "autogen"
brew "binutils"
brew "coreutils"
brew "cmake"
brew "pkg-config"
brew "boost"
brew "openssl"
brew "hidapi"
brew "zmq"
brew "unbound"
brew "libsodium"
brew "readline"
brew "ccache"
brew "rust"
brew "doxygen"
brew "graphviz"
# no libunwind: macOS builds never take the libunwind stack-trace path (CMakeLists.txt
# disables it for APPLE), and Homebrew deprecated libunwind-headers as unmaintained
brew "protobuf"
brew "libusb"
